name: procal
description: "The protein and calorie tracker"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.5.3
  freezed: ^3.0.6
  go_router: ^15.2.0
  health: ^13.1.0
  hooks_riverpod: ^2.5.4
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.3
  simple_barcode_scanner: ^0.3.0
  toastification: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
