name: procal
description: "The protein and calorie tracker"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dev: ^1.0.0
  dio: ^5.8.0+1
  firebase_ai: ^3.1.0
  firebase_auth: ^6.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^3.0.0
  flutter_svg: ^2.0.13
  freezed: ^3.0.6
  go_router: ^16.0.0
  health: ^13.1.0
  hooks_riverpod: ^3.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.3.0
  retrofit: ^4.6.0
  riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  shared_preferences: ^2.3.3
  simple_barcode_scanner: ^0.3.0
  toastification: ^3.0.1

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  retrofit_generator: ^10.0.0
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - dev.env
    - local.env

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
